name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }
jobs:
  smoke:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "CI wired up ✅"
